name: 🛠️ Test Minecraft Server with Mods

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-minecraft-server:
    runs-on: ubuntu-latest

    steps:
      # 📂 Repository auschecken
      - name: 📂 Checkout repository
        uses: actions/checkout@v3

      # ☕ Java 21 installieren
      - name: ☕ Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Minecraft benötigt Java 21

      # 📂 Kopiere Mods aus dem Repository (ohne redundantes Kopieren)
      - name: 📂 Copy Mods from Repository
        run: |
          mkdir -p mods
          find ./mods -type f -name "*.jar" -exec cp {} ./mods/ \;

      # ⬇️ Mods aus mods.txt herunterladen
      - name: ⬇️ Download Mods from mods.txt
        run: |
          mkdir -p mods
          while IFS= read -r slug; do
            if [ ! -z "$slug" ]; then
              echo "Downloading mod: $slug"
              curl -s "https://api.modrinth.com/v2/project/$slug/version" | jq -r '.[0].files[0].url' | xargs -n 1 curl -O -J
              mv *.jar mods/
            fi
          done < mods.txt

      # ⬇️ Download Fabric Server Launcher
      - name: ⬇️ Download Fabric Server Launcher
        run: |
          curl -OJ https://meta.fabricmc.net/v2/versions/loader/1.21.4/0.16.12/1.0.3/server/jar
          mv fabric-server-mc.1.21.4-loader.0.16.12-launcher.1.0.3.jar server.jar

      # ✅ Accept Minecraft EULA
      - name: ✅ Accept Minecraft EULA
        run: echo "eula=true" > eula.txt

      # 🚀 Server starten
      - name: 🚀 Start Minecraft Server
        run: |
          java -Xmx2G -jar server.jar nogui &
          sleep 30 # Warte, bis der Server vollständig gestartet ist

      # ✅ Überprüfen, ob der Server läuft
      - name: ✅ Check Server Status
        run: |
          if pgrep -f "server.jar" > /dev/null; then
            echo "✅ Server is running successfully!"
          else
            echo "❌ Server failed to start."
            exit 1
          fi