name: 🧪 Test All Mods from mods.txt

on:
  workflow_dispatch:

jobs:
  test-mod-download:
    runs-on: ubuntu-latest

    steps:
      # 📂 Repository auschecken
      - name: 📂 Checkout repository
        uses: actions/checkout@v3

      # 📄 Mods aus mods.txt herunterladen und testen
      - name: ⬇️ Test Mod Downloads from mods.txt
        run: |
          mkdir -p test-mods
          echo "Testing downloads for all mods in mods.txt..."
          while IFS= read -r slug; do
            if [ ! -z "$slug" ]; then
              echo "Testing download for mod: $slug"
              curl -s "https://api.modrinth.com/v2/project/$slug/version" | jq -r '.[0].files[0].url' | xargs -n 1 curl -O -J -o test-mods/$slug.jar
              if [ -f "test-mods/$slug.jar" ]; then
                echo "✅ Mod $slug downloaded successfully!"
              else
                echo "❌ Failed to download mod $slug."
                exit 1
              fi
            fi
          done < mods.txt